from art import *
print("Butterfly by art: ",end=" ")
aprint("butterfly")
print()
Art=text2art("DIAR",font='block',chr_ignore=True)
print(Art)
tprint("DIAR","rnd-xlarge")
tprint("DIAR","random")
tprint("DIAR","rand")
tsave("DIAR",filename="Output_in_txt().txt")
tprint("DIAR")
art_=art("woman",number=2)
print(art_)
print(art("random"))
#